// Country code to name mapping for common countries
export const countryNames: Record<string, string> = {
  'US': 'United States',
  'CN': 'China',
  'IN': 'India',
  'BR': 'Brazil',
  'RU': 'Russia',
  'JP': 'Japan',
  'DE': 'Germany',
  'GB': 'United Kingdom',
  'FR': 'France',
  'IT': 'Italy',
  'CA': 'Canada',
  'AU': 'Australia',
  'ES': 'Spain',
  'MX': 'Mexico',
  'KR': 'South Korea',
  'NL': 'Netherlands',
  'SE': 'Sweden',
  'PL': 'Poland',
  'BE': 'Belgium',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'NO': 'Norway',
  'DK': 'Denmark',
  'FI': 'Finland',
  'PT': 'Portugal',
  'GR': 'Greece',
  'CZ': 'Czech Republic',
  'HU': 'Hungary',
  'RO': 'Romania',
  'SK': 'Slovakia',
  'BG': 'Bulgaria',
  'HR': 'Croatia',
  'SI': 'Slovenia',
  'LT': 'Lithuania',
  'LV': 'Latvia',
  'EE': 'Estonia',
  'IE': 'Ireland',
  'AR': 'Argentina',
  'CL': 'Chile',
  'CO': 'Colombia',
  'PE': 'Peru',
  'VE': 'Venezuela',
  'UY': 'Uruguay',
  'EC': 'Ecuador',
  'BO': 'Bolivia',
  'PY': 'Paraguay',
  'ZA': 'South Africa',
  'EG': 'Egypt',
  'NG': 'Nigeria',
  'KE': 'Kenya',
  'MA': 'Morocco',
  'TN': 'Tunisia',
  'DZ': 'Algeria',
  'GH': 'Ghana',
  'UG': 'Uganda',
  'TZ': 'Tanzania',
  'ZW': 'Zimbabwe',
  'TR': 'Turkey',
  'SA': 'Saudi Arabia',
  'AE': 'United Arab Emirates',
  'IL': 'Israel',
  'JO': 'Jordan',
  'LB': 'Lebanon',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'KW': 'Kuwait',
  'QA': 'Qatar',
  'BH': 'Bahrain',
  'OM': 'Oman',
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'SG': 'Singapore',
  'MY': 'Malaysia',
  'ID': 'Indonesia',
  'PH': 'Philippines',
  'BD': 'Bangladesh',
  'PK': 'Pakistan',
  'LK': 'Sri Lanka',
  'MM': 'Myanmar',
  'KH': 'Cambodia',
  'LA': 'Laos',
  'NP': 'Nepal',
  'BT': 'Bhutan',
  'MV': 'Maldives',
  'MN': 'Mongolia',
  'KZ': 'Kazakhstan',
  'UZ': 'Uzbekistan',
  'KG': 'Kyrgyzstan',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'AF': 'Afghanistan',
  'NZ': 'New Zealand',
  'FJ': 'Fiji',
  'PG': 'Papua New Guinea',
  'NC': 'New Caledonia',
  'SB': 'Solomon Islands',
  'VU': 'Vanuatu',
  'WS': 'Samoa',
  'TO': 'Tonga',
  'KI': 'Kiribati',
  'TV': 'Tuvalu',
  'NR': 'Nauru',
  'PW': 'Palau',
  'FM': 'Micronesia',
  'MH': 'Marshall Islands'
};

export function getCountryName(countryCode: string): string {
  return countryNames[countryCode.toUpperCase()] || countryCode;
}

// Get color class based on score for map visualization
export function getCountryColorClass(score: number, maxScore: number): string {
  if (score === 0) return 'country-none';
  
  const percentage = (score / maxScore) * 100;
  
  if (percentage >= 80) return 'country-high';
  if (percentage >= 60) return 'country-medium-high';
  if (percentage >= 30) return 'country-medium';
  return 'country-low';
}